---
galaxy_info:
  role_name: brave
  author: egvimo
  description: Installs Brave Browser

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - brave
