---
- name: Gather package facts
  package_facts:
    manager: auto

- name: Install dependencies
  apt:
    name: gpg
    update_cache: yes
    state: present
  become: yes
  when: "'code' not in ansible_facts.packages"

- name: Install Visual Studio Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  become: yes
  when: "'code' not in ansible_facts.packages"
