---
- name: Install dependencies
  apt:
    name: gpg
    update_cache: yes
    state: present
  become: yes

- include_role:
    name: apt_installer
  vars:
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    repository: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
    repository_name: vscode
    package_name: code
