galaxy_info:
  role_name: apt_installer
  author: egvimo
  description: Installer for packages not in the main repositories

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - apt

dependencies: []
