---
dependencies: []

galaxy_info:
  role_name: vs_code
  author: egvimo
  description: Installs Visual Studio Code

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - vscode
