namespace: egvimo
name: general
version: "0.5.1"
description: Collection of miscellaneous roles

authors:
  - egvimo

readme: README.md
license_file: LICENSE

tags:
  - bash_it
  - chrome
  - docker
  - git_server
  - jdownloader
  - minidlna
  - pi_hole
  - raspberry
  - vs_code

dependencies:
  community.general: ">=1.0.0"

repository: https://github.com/egvimo/ansible-collection-general
documentation: https://github.com/egvimo/ansible-collection-general
homepage: https://github.com/egvimo/ansible-collection-general
issues: https://github.com/egvimo/ansible-collection-general/issues
