---
- name: "Add '{{ user_name }}' user"
  ansible.builtin.user:
    name: "{{ user_id }}"
    comment: "{{ user_name }}"
  become: yes

- name: "Add '{{ ansible_user }}' to '{{ user_id }}' group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ user_id }}"
    append: yes
  become: yes
  when:
    - ansible_user is defined
    - user_add_ansible_user_to_group

- name: "Get '{{ user_id }}' user info"
  ansible.builtin.getent:
    database: passwd
    key: "{{ user_id }}"

- name: "Set uid, gid and home for user '{{ user_id }}'"
  ansible.builtin.set_fact:
    user_uid: "{{ getent_passwd[user_id].1 }}"
    user_gid: "{{ getent_passwd[user_id].2 }}"
    user_home: "{{ getent_passwd[user_id].4 }}"
