---
- name: "Add '{{ user_name }}' user"
  user:
    name: "{{ user_id }}"
    comment: "{{ user_name }}"
  become: yes

- name: "Add '{{ ansible_user }}' to '{{ user_id }}' group"
  user:
    name: "{{ ansible_user }}"
    groups: "{{ user_id }}"
    append: yes
  become: yes
  when:
    - ansible_user is defined
    - user_add_ansible_user_to_group

- name: "Get '{{ user_id }}' user info"
  getent:
    database: passwd
    key: "{{ user_id }}"

- name: "Set uid and gid for user '{{ user_id }}'"
  set_fact:
    user_uid: "{{ getent_passwd[user_id].1 }}"
    user_gid: "{{ getent_passwd[user_id].2 }}"
