galaxy_info:
  role_name: chrome
  author: egvimo
  description: Installs Google Chrome

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - chrome

dependencies: []
