---
- block:
    - name: Install required packages
      apt:
        pkg:
          - gnupg
        update_cache: yes

    - name: Add key
      apt_key:
        url: "{{ apt_key_url }}"
        state: present

    - name: Add repository
      apt_repository:
        repo: "{{ apt_repository }}"
        filename: "{{ apt_repository_name }}"
        update_cache: yes
        state: present

    - name: "Install '{{ apt_package_name }}'"
      apt:
        name: "{{ apt_package_name }}"
        state: present
  become: yes
