---
- name: Ensure bash-completion is installed
  ansible.builtin.apt:
    name: bash-completion
    update_cache: yes
    state: present
  become: true

- name: Create kubectl completion file
  ansible.builtin.shell: kubectl completion bash > kubectl
  args:
    chdir: /etc/bash_completion.d
    creates: /etc/bash_completion.d/kubectl
  become: true
