---
- name: Download K3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/latest/download/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/latest/download/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"

- name: Copy K3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: "0755"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create directory .kube
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "0600"

- name: Replace https://localhost:6443 by https://<k3s_master_ip>:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_master_ip }}:6443
      --kubeconfig /home/{{ ansible_user }}/.kube/config
  changed_when: true
  when: k3s_master_ip is defined

- name: Create symlinks
  file:
    src: /usr/local/bin/k3s
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectl
    - crictl
    - ctr
