---
galaxy_info:
  role_name: kubectl
  author: egvimo
  description: Installation of kubectl command-line tool

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - kubectl
