---
- name: Clone Bash-it repository
  ansible.builtin.git:
    repo: "{{ bash_it_repository }}"
    dest: "{{ bash_it_user_home }}/.bash_it"
    version: "{{ bash_it_version }}"
    depth: 1
  become: yes
  become_user: "{{ bash_it_user }}"

- name: Run installer
  ansible.builtin.command:
    cmd: "{{ bash_it_user_home }}/.bash_it/install.sh --silent --no-modify-config"
    creates: "{{ bash_it_user_home }}/.bash_it/enabled"

- name: Add Bash-it configuration to .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ bash_it_user_home }}/.bashrc"
    create: yes
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    owner: "{{ bash_it_user }}"
    mode: '644'
  loop:
    - { regexp: '^export BASH_IT=', line: "export BASH_IT={{ bash_it_user_home }}/.bash_it" }
    - { regexp: '^export BASH_IT_THEME=', line: "export BASH_IT_THEME={{ bash_it_theme }}" }
    - { regexp: '^source \$BASH_IT', line: "source $BASH_IT/bash_it.sh" }

- name: Ensure .bash_profile sources .bashrc
  ansible.builtin.blockinfile:
    dest: "{{ bash_it_user_home }}/.bash_profile"
    create: yes
    block: |
      if [ -f ~/.bashrc ]; then
        . ~/.bashrc
      fi
    owner: "{{ bash_it_user }}"
    mode: '644'
