---
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python
      apt:
        pkg:
          - python3
          - python3-pip
        update_cache: yes
        state: present
    - name: Install docker python package
      pip:
        name: docker
