---
- block:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true
  become: yes
  tags: docker
