---
galaxy_info:
  role_name: bash_it
  author: egvimo
  description: Installation of Bash-it framework

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all

  galaxy_tags:
    - linux
    - unix
    - bash
    - shell
