---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: user
      vars:
        user_id: alice
        user_name: Alice
    - name: Include role
      include_role:
        name: user
      vars:
        user_id: bob
        user_name: Bob
        user_add_ansible_user_to_group: true
        ansible_user: root
